env_file: mpe.spread_target
env_class: SpreadTargetMPE
scenario_name: "spread"

max_ep_len: 100
n_agents: 2
n_tasks: 3
task_info_dim: 3

save_name: "spread"

ae_batch_size: 100
ae_updates_per_iter: 50
n_init_rollouts: 5  # n_init_rollouts * n_envs 填充 ae_buffer
ae_buffer_size: 1000

ppo_epoch: 15
n_rollout_threads: 32
n_ae_rollout_threads: 4

