env_file: mm_rware.rware_layout
env_class: MultiMapRware
difficulty: ""  # "-easy", "", "-hard"
sensor_range: 2

max_ep_len: 100
n_agents: 4
n_tasks: 5

save_name: "mm_rware"

ae_batch_size: 64
ae_updates_per_iter: 20
n_init_rollouts: 10  # n_init_rollouts * n_envs 填充 ae_buffer
ae_buffer_size: 2000

ppo_epoch: 15
n_rollout_threads: 32
n_ae_rollout_threads: 4


layouts:
  - |
    ..........
    ..xx..xx..
    ..xx..xx..
    ..xx..xx..
    ..xx..xx..
    ..xx..xx..
    ..xx..xx..
    ..xx..xx..
    ..........
    ....gg....
  - |
    ..........
    ......xx..
    ......xx..
    ......xx..
    ......xx..
    ......xx..
    ......xx..
    ......xx..
    ..........
    ....gg....
  - |
    ..........
    ..xx......
    ..xx......
    ..xx......
    ..xx......
    ..xx......
    ..xx......
    ..xx......
    ..........
    ....gg....
  - |
    ..........
    ..xx..xx..
    ..xx..xx..
    ..xx..xx..
    ..xx..xx..
    ..........
    ..........
    ..........
    ..........
    ....gg....
  - |
    ..........
    ..........
    ..........
    ..........
    ..xx..xx..
    ..xx..xx..
    ..xx..xx..
    ..xx..xx..
    ..........
    ....gg....
    
    
    
    
