algo_name: "mg2l"

# prepare parameters
n_training_threads: 32

# env parameters
use_obs_instead_of_state: false

# network parameters
share_policy: false
use_centralized_V: true
use_stacked_frames: false
stacked_frames: 1
algo_hidden_size: 256
layer_N: 1
use_ReLU: true
use_popart: false
use_valuenorm: true
use_feature_normalization: true
use_orthogonal: true
gain: 0.01

# recurrent parameters
use_recurrent_policy: false
use_naive_recurrent_policy: false
recurrent_N: 1
data_chunk_length: 10

# optimizer parameters
actor_lr: 5e-4
critic_lr: 5e-4
opti_eps: 1e-5
weight_decay: 0

# ppo parameters
use_clipped_value_loss: true
clip_param: 0.2
num_mini_batch: 1
entropy_coef: 0.01
value_loss_coef: 1
use_max_grad_norm: true
max_grad_norm: 10.0
use_gae: true
gamma: 0.99
gae_lambda: 0.95
use_proper_time_limits: false
use_huber_loss: true
use_value_active_masks: true
use_policy_active_masks: true
huber_delta: 10.0

# run parameters
use_linear_lr_decay: true





